services:

  shopee:
    image: shopee
    container_name: shopee
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    user: node
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./.env:/app/.env
    restart: always
    tty: true
    networks:
      - app-network
  pinger:
    image: busybox
    container_name: pinger
    entrypoint: ping -c 4 shopee
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
